---
title: "Data Collection"
output: html_document
author: "C. Beattie, Sam Rudenberg, K. Shah" 
date: '2023-12-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries 
```{r}
library(psych)
library(factoextra)
library(ggplot2)
library(dplyr)
library(corrplot)
library(Rblpapi)
library(dplyr)
```


# Tickers_500
```{r}
tickers_500 <- c(
  "MMM US Equity", "AOS US Equity", "ABT US Equity", "ABBV US Equity", 
  "ACN US Equity", "ADBE US Equity", "AMD US Equity", "AES US Equity", 
  "AFL US Equity", "A US Equity", "APD US Equity", "ABNB US Equity", 
  "AKAM US Equity", "ALK US Equity", "ALB US Equity", "ARE US Equity", 
  "ALGN US Equity", "ALLE US Equity", "LNT US Equity", "ALL US Equity", 
  "GOOGL US Equity", "GOOG US Equity", "MO US Equity", "AMZN US Equity", 
  "AMCR US Equity", "AEE US Equity", "AAL US Equity", "AEP US Equity", 
  "AXP US Equity", "AIG US Equity", "AMT US Equity", "AWK US Equity", 
  "AMP US Equity", "AME US Equity", "AMGN US Equity", "APH US Equity", 
  "ADI US Equity", "ANSS US Equity", "AON US Equity", "APA US Equity", 
  "AAPL US Equity", "AMAT US Equity", "APTV US Equity", "ACGL US Equity", 
  "ADM US Equity", "ANET US Equity", "AJG US Equity", "AIZ US Equity", 
  "T US Equity", "ATO US Equity", "ADSK US Equity", "ADP US Equity", 
  "AZO US Equity", "AVB US Equity", "AVY US Equity", "AXON US Equity", 
  "BKR US Equity", "BALL US Equity", "BAC US Equity", "BK US Equity", 
  "BBWI US Equity", "BAX US Equity", "BDX US Equity", "BRK.B US Equity", 
  "BBY US Equity", "BIO US Equity", "TECH US Equity", "BIIB US Equity", 
  "BLK US Equity", "BX US Equity", "BA US Equity", "BKNG US Equity", 
  "BWA US Equity", "BXP US Equity", "BSX US Equity", "BMY US Equity", 
  "AVGO US Equity", "BR US Equity", "BRO US Equity", "BF.B US Equity", 
  "BG US Equity", "CDNS US Equity", "CZR US Equity", "CPT US Equity", 
  "CPB US Equity", "COF US Equity", "CAH US Equity", "KMX US Equity", 
  "CCL US Equity", "CARR US Equity", "CTLT US Equity", "CAT US Equity", 
  "CBOE US Equity", "CBRE US Equity", "CDW US Equity", "CE US Equity", 
  "COR US Equity", "CNC US Equity", "CNP US Equity", "CDAY US Equity", 
  "CF US Equity", "CHRW US Equity", "CRL US Equity", "SCHW US Equity", 
  "CHTR US Equity", "CVX US Equity", "CMG US Equity", "CB US Equity", 
  "CHD US Equity", "CI US Equity", "CINF US Equity", "CTAS US Equity", 
  "CSCO US Equity", "C US Equity", "CFG US Equity", "CLX US Equity", 
  "CME US Equity", "CMS US Equity", "KO US Equity", "CTSH US Equity", 
  "CL US Equity", "CMCSA US Equity", "CMA US Equity", "CAG US Equity", 
  "COP US Equity", "ED US Equity", "STZ US Equity", "CEG US Equity", 
  "COO US Equity", "CPRT US Equity", "GLW US Equity", "CTVA US Equity", 
  "CSGP US Equity", "COST US Equity", "CTRA US Equity", "CCI US Equity", 
  "CSX US Equity", "CMI US Equity", "CVS US Equity", "DHR US Equity", 
  "DRI US Equity", "DVA US Equity", "DE US Equity", "DAL US Equity", 
  "XRAY US Equity", "DVN US Equity", "DXCM US Equity", "FANG US Equity", 
  "DLR US Equity", "DFS US Equity", "DG US Equity", "DLTR US Equity", 
  "D US Equity", "DPZ US Equity", "DOV US Equity", "DOW US Equity", 
  "DHI US Equity", "DTE US Equity", "DUK US Equity", "DD US Equity", 
  "EMN US Equity", "ETN US Equity", "EBAY US Equity", 
  "ECL US Equity", "EIX US Equity", "EW US Equity", "EA US Equity", 
  "ELV US Equity", "LLY US Equity", "EMR US Equity", "ENPH US Equity", 
  "ETR US Equity", "EOG US Equity", "EPAM US Equity", "EQT US Equity", 
  "EFX US Equity", "EQIX US Equity", "EQR US Equity", "ESS US Equity", 
  "EL US Equity", "ETSY US Equity", "EG US Equity", "EVRG US Equity", 
  "ES US Equity", "EXC US Equity", "EXPE US Equity", "EXPD US Equity", 
  "EXR US Equity", "XOM US Equity", "FFIV US Equity", "FDS US Equity", 
  "FICO US Equity", "FAST US Equity", "FRT US Equity", "FDX US Equity", 
  "FIS US Equity", "FITB US Equity", "FSLR US Equity", "FE US Equity", 
  "FI US Equity", "FLT US Equity", "FMC US Equity", "F US Equity", 
  "FTNT US Equity", "FTV US Equity", "FOXA US Equity", "FOX US Equity", 
  "BEN US Equity", "FCX US Equity", "GRMN US Equity", "IT US Equity", 
  "GEHC US Equity", "GEN US Equity", "GNRC US Equity", "GD US Equity", 
  "GE US Equity", "GIS US Equity", "GM US Equity", "GPC US Equity", 
  "GILD US Equity", "GPN US Equity", "GL US Equity", "GS US Equity", 
  "HAL US Equity", "HIG US Equity", "HAS US Equity", "HCA US Equity", 
  "PEAK US Equity", "HSIC US Equity", "HSY US Equity", "HES US Equity", 
  "HPE US Equity", "HLT US Equity", "HOLX US Equity", "HD US Equity", 
  "HON US Equity", "HRL US Equity", "HST US Equity", "HWM US Equity", 
  "HPQ US Equity", "HUBB US Equity", "HUM US Equity", "HBAN US Equity", 
  "HII US Equity", "IBM US Equity", "IEX US Equity", "IDXX US Equity", 
  "ITW US Equity", "ILMN US Equity", "INCY US Equity", "IR US Equity", 
  "PODD US Equity", "INTC US Equity", "ICE US Equity", "IFF US Equity", 
  "IP US Equity", "IPG US Equity", "INTU US Equity", "ISRG US Equity", 
  "IVZ US Equity", "INVH US Equity", "IQV US Equity", "IRM US Equity", 
  "JBHT US Equity", "JKHY US Equity", "J US Equity", "JNJ US Equity", 
  "JCI US Equity", "JPM US Equity", "JNPR US Equity", "K US Equity", 
  "KVUE US Equity", "KDP US Equity", "KEY US Equity", "KEYS US Equity", 
  "KMB US Equity", "KIM US Equity", "KMI US Equity", "KLAC US Equity", 
  "KHC US Equity", "KR US Equity", "LHX US Equity", "LH US Equity", 
  "LRCX US Equity", "LW US Equity", "LVS US Equity", "LDOS US Equity", 
  "LEN US Equity", "LIN US Equity", "LYV US Equity", "LKQ US Equity", 
  "LMT US Equity", "L US Equity", "LOW US Equity", "LULU US Equity", 
  "LYB US Equity", "MTB US Equity", "MRO US Equity", "MPC US Equity", 
  "MKTX US Equity", "MAR US Equity", "MMC US Equity", "MLM US Equity", 
  "MAS US Equity", "MA US Equity", "MTCH US Equity", "MKC US Equity", 
  "MCD US Equity", "MCK US Equity", "MDT US Equity", "MRK US Equity", 
  "META US Equity", "MET US Equity", "MTD US Equity", "MGM US Equity", 
  "MCHP US Equity", "MU US Equity", "MSFT US Equity", "MAA US Equity",
  "MRNA US Equity", "MHK US Equity", 
  "MOH US Equity", "TAP US Equity", "MDLZ US Equity", "MPWR US Equity", 
  "MNST US Equity", "MCO US Equity", "MS US Equity", "MOS US Equity", 
  "MSI US Equity", "MSCI US Equity", "NDAQ US Equity", "NTAP US Equity", 
  "NFLX US Equity", "NEM US Equity", "NWSA US Equity", "NWS US Equity", 
  "NEE US Equity", "NKE US Equity", "NI US Equity", "NDSN US Equity", 
  "NSC US Equity", "NTRS US Equity", "NOC US Equity", "NCLH US Equity", 
  "NRG US Equity", "NUE US Equity", "NVDA US Equity", "NVR US Equity", 
  "NXPI US Equity", "ORLY US Equity", "OXY US Equity", "ODFL US Equity", 
  "OMC US Equity", "ON US Equity", "OKE US Equity", "ORCL US Equity", 
  "OTIS US Equity", "PCAR US Equity", "PKG US Equity", "PANW US Equity", 
  "PARA US Equity", "PH US Equity", "PAYX US Equity", "PAYC US Equity", 
  "PYPL US Equity", "PNR US Equity", "PEP US Equity", "PFE US Equity", 
  "PCG US Equity", "PM US Equity", "PSX US Equity", "PNW US Equity", 
  "PXD US Equity", "PNC US Equity", "POOL US Equity", "PPG US Equity", 
  "PPL US Equity", "PFG US Equity", "PG US Equity", "PGR US Equity", 
  "PLD US Equity", "PRU US Equity", "PEG US Equity", "PTC US Equity", 
  "PSA US Equity", "PHM US Equity", "QRVO US Equity", "PWR US Equity", 
  "QCOM US Equity", "DGX US Equity", "RL US Equity", "RJF US Equity", 
  "RTX US Equity", "O US Equity", "REG US Equity", "REGN US Equity", 
  "RF US Equity", "RSG US Equity", "RMD US Equity", "RVTY US Equity", 
  "RHI US Equity", "ROK US Equity", "ROL US Equity", "ROP US Equity", 
  "ROST US Equity", "RCL US Equity", "SPGI US Equity", "CRM US Equity", 
  "SBAC US Equity", "SLB US Equity", "STX US Equity", "SEE US Equity", 
  "SRE US Equity", "NOW US Equity", "SHW US Equity", "SPG US Equity", 
  "SWKS US Equity", "SJM US Equity", "SNA US Equity", "SEDG US Equity", 
  "SO US Equity", "LUV US Equity", "SWK US Equity", "SBUX US Equity", 
  "STT US Equity", "STLD US Equity", "STE US Equity", "SYK US Equity", 
  "SYF US Equity", "SNPS US Equity", "SYY US Equity", "TMUS US Equity", 
  "TROW US Equity", "TTWO US Equity", "TPR US Equity", "TRGP US Equity", 
  "TGT US Equity", "TEL US Equity", "TDY US Equity", "TFX US Equity", 
  "TER US Equity", "TSLA US Equity", "TXN US Equity", "TXT US Equity", 
  "TMO US Equity", "TJX US Equity", "TSCO US Equity", "TT US Equity", 
  "TDG US Equity", "TRV US Equity", "TRMB US Equity", "TFC US Equity", 
  "TYL US Equity", "TSN US Equity", "USB US Equity", "UDR US Equity", 
  "ULTA US Equity", "UNP US Equity", "UAL US Equity", "UPS US Equity", 
  "URI US Equity", "UNH US Equity", "UHS US Equity", "VLO US Equity", 
  "VTR US Equity", "VLTO US Equity", "VRSN US Equity", "VRSK US Equity", 
  "VZ US Equity", "VRTX US Equity", "VFC US Equity", "VTRS US Equity", 
  "VICI US Equity", "V US Equity", "VMC US Equity", "WRB US Equity", 
  "WAB US Equity", "WBA US Equity", "WMT US Equity", "DIS US Equity", 
  "WBD US Equity", "WM US Equity", "WAT US Equity", "WEC US Equity", 
  "WFC US Equity", "WELL US Equity", "WST US Equity", "WDC US Equity", 
  "WRK US Equity", "WY US Equity", "WHR US Equity", "WMB US Equity", 
  "WTW US Equity", "GWW US Equity", "WYNN US Equity", "XEL US Equity", 
  "XYL US Equity", "YUM US Equity", "ZBRA US Equity", "ZBH US Equity", 
  "ZION US Equity", "ZTS US Equity"
)
```


# Connecting to Bloomberg & Pulling Data 
```{r}
library(Rblpapi)

# Connect to Bloomberg Terminal
con <- blpConnect()

# Define tickers and fields
fields <- c("PX_LAST", "PE_RATIO", "BS_TOT_ASSET", "BS_CUR_ASSET_REPORT", "BS_TOT_LIAB2", 
            "BS_CUR_LIAB", "SALES_REV_TURN", "EBIT", "CF_CASH_FROM_OPER", 
            "CF_CASH_FROM_INV_ACT", "CF_CASH_FROM_FNC_ACT", "BS_CASH_NEAR_CASH_ITEM", 
            "CAPITAL_EXPEND", "PX_TO_BOOK_RATIO", "BOOK_VAL_PER_SH", "CASH_FLOW_PER_SH", 
            "CUR_RATIO", "PROF_MARGIN", "RETURN_ON_ASSET", "IS_EPS", "CUR_MKT_CAP")

# Initialize a list to store data frames for each ticker
all_data <- list()
i = 0
# Loop over each ticker and retrieve quarterly historical data
for (ticker in tickers_500) {
  tryCatch({
    # Retrieve historical data
    data <- bdh(securities = ticker, fields = fields, 
                start.date = as.Date("2000-01-01"), 
                end.date = Sys.Date(),
                options = c("periodicitySelection" = "QUARTERLY"))
    
    # If data retrieval is successful, store the data frame in the list
    if (!is.null(data)) {
      all_data[[ticker]] <- data
    }
  }, error = function(e) {
    message(sprintf("Error retrieving data for %s: %s", ticker, e$message))
  })
  i = i + 1
  print(paste0(i , " # Ticker = ", ticker))
}

# Combine all individual ticker data frames into one
combined_data_500 <- do.call(rbind, all_data)

# Print the combined dataframe to verify the data
print(combined_data)

# Disconnect from Bloomberg Terminal
blpDisconnect(con)
```


# Writing to a file 
```{r}
data_w_names <- rownames_to_column(combined_data_500, "Ticker")
write.csv(data_w_names, "combined_data_500.csv")
```

